#!/bin/bash

i3lock --insidever-color=101010bf --insidewrong-color=101010bf --inside-color=101010bf --ringver-color=30309bff --ringwrong-color=dd1818ff --ring-color=30309bff --verif-color=c7d9dbbb --wrong-color=c7d9dbbb --line-color=00000000 --keyhl-color=115cddff --bshl-color=bc0303ff --separator-color=ffffff00 --radius=300 -e -i ~/Pictures/Wallpaper_Scaled.png

