#!/bin/sh

player_status=$(playerctl status 2> /dev/null)

if [ "$player_status" = "Playing" ]; then
	if [ "$(playerctl metadata artist)" = "" ]; then
		echo "%{F#ccffffff}   $(playerctl metadata title)"
	else
		echo "%{F#ccffffff}   $(playerctl metadata artist)  -  $(playerctl metadata title)"
	fi
elif [ "$player_status" = "Paused" ]; then
	if [ "$(playerctl metadata artist)" = "" ]; then
		echo "%{F#66}   $(playerctl metadata title)"
	else
		echo "%{F#66}   $(playerctl metadata artist)  -  $(playerctl metadata title)"
	fi
else
	echo ""
fi

