#!/bin/bash

for file in ~/* \
			~/.bin \
			~/.config/kalu \
			~/.config/Mousepad \
			~/.config/polybar \
			~/.config/qalculate \
			~/.config/rofi \
			~/.config/alacritty \
            ~/.config/nvim \
			~/.config/Thunar \
			~/.config/rclone \
			~/.config/user-dirs.dirs \
			~/.config/numix-folders \
			~/.config/gtk-3.0 \
			~/.config/i3 \
			~/.config/dunst \
			~/.config/xfce4 \
			~/.vim/ycm_extra_conf.py \
			~/.vim/colors/neodark.vim \
			~/.vim/autoload \
			~/.vim/after \
			~/.gdbinit \
			~/.gtkrc-2.0 \
			~/.hidden \
			~/.vimrc \
			~/.zshrc \
			~/.vimspector.json \
			/etc/default/grub \
			/etc/mkinitcpio.conf \
			/etc/lightdm/lightdm-gtk-greeter.conf \
			/etc/lightdm/Sketch_PFP_Discord.png \
			/etc/lightdm/Wallpaper.png \
			/usr/share/themes/Arc-Undead-Custom; do
	echo "############### Backup ${file} ###############"
	rclone sync -l -v --transfers 30 ${file} google-drive:Backup${file} --backup-dir google-drive:Backup/OLD${file}
done

