#!/bin/bash

for file in ~/* \
			~/.bin \
			~/.config/kalu \
			~/.config/Mousepad \
			~/.config/polybar \
			~/.config/qalculate \
			~/.config/rofi \
			~/.config/alacritty \
            ~/.config/nvim \
			~/.config/Thunar \
			~/.config/rclone \
			~/.config/user-dirs.dirs \
			~/.config/numix-folders \
			~/.config/gtk-3.0 \
			~/.config/i3 \
			~/.config/dunst \
			~/.config/xfce4 \
			~/.gtkrc-2.0 \
			~/.hidden \
            ~/.themes \
			~/.zshrc \
			/etc/default/grub \
            /boot/grub/grub.cfg \
			/etc/mkinitcpio.conf \
			/etc/lightdm/lightdm-gtk-greeter.conf \
			/etc/lightdm/Sketch_PFP_Discord.png \
			/etc/lightdm/Wallpaper.png; do
	echo "############### Backup ${file} ###############"
	rclone sync -l -v --transfers 30 ${file} google-drive:Backup${file} --backup-dir google-drive:Backup/OLD${file}
done

