#!/bin/bash

while test $# -gt 0; do
	case "$1" in
		-m)
			( echo "############### yay-sip -m ###############"; echo "---------- NORMAL PACKAGES ----------"; yay -Qqen; echo "---------- AUR PACKAGES ----------"; yay -Qqem ) | less
			exit 0;;
		-e)
			( echo "############### yay-sip -e ###############"; echo "---------- NORMAL PACKAGES ----------"; comm -23 <(pacman -Qqten | sort) <(pacman -Qqg | sort | uniq); echo "---------- AUR PACKAGES ----------"; comm -23 <(pacman -Qqtem | sort) <(pacman -Qqg | sort | uniq) ) | less
			exit 0;;
		-me)
			( echo "############### yay-sip -me ###############"; echo "---------- NORMAL PACKAGES ----------"; comm -23 <(pacman -Qqen | sort) <(pacman -Qqg | sort | uniq); echo "---------- AUR PACKAGES ----------"; comm -23 <(pacman -Qqem | sort) <(pacman -Qqg | sort | uniq) ) | less
			exit 0;;
		-a)
			( ~/.bin/yay-sip; echo ""; ~/.bin/yay-sip -m; echo ""; ~/.bin/yay-sip -e; echo ""; ~/.bin/yay-sip -me; ) | less
			exit 0;;
		-as)
			( ~/.bin/yay-sip; echo ""; ~/.bin/yay-sip -m; echo ""; ~/.bin/yay-sip -e; echo ""; ~/.bin/yay-sip -me; ) > ~/.bin/Packages
			exit 0;;
		*)
			break;;
	esac
done

#No Flags
( echo -e "############### yay-sip ###############"; echo "---------- NORMAL PACKAGES ----------"; yay -Qqten; echo "---------- AUR PACKAGES ----------"; yay -Qqtem ) | less

