#!/bin/bash

while test $# -gt 0; do
	case "$1" in
		-m)
			( echo "---------- NORMAL PACKAGES ----------"; yay -Qqen; echo "---------- AUR PACKAGES ----------"; yay -Qqem ) | less
			exit 0;;
		--more)
			( echo "---------- NORMAL PACKAGES ----------"; yay -Qqen; echo "---------- AUR PACKAGES ----------"; yay -Qqem ) | less
			exit 0;;
		*)
			break;;
	esac
done

#No Flags
( echo "---------- NORMAL PACKAGES ----------"; yay -Qqten; echo "---------- AUR PACKAGES ----------"; yay -Qqtem ) | less

